apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: influx
  name: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - image: telegraf:1.24.2
          name: telegraf
          envFrom:
            - secretRef:
                name: telegraf-secrets
          volumeMounts:
            - name: telegraf-config-volume
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
              readOnly: true
            - name: file-path
              mountPath: /file

      volumes:
        - name: telegraf-config-volume
          configMap:
            name: telegraf-config
        - name: file-path
          hostPath:
            path: /home/jhim/kube-influx/telegraf
            type: DirectoryOrCreate
