apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: influxdb
  name: influxdb
  namespace: influx
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: influxdb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: influxdb
    spec:
      containers:
        - image: influxdb:1.8
          imagePullPolicy: IfNotPresent
          name: influxdb
          volumeMounts:
          - mountPath: /var/lib/influxdb
            name: influxdb
          envFrom:
          - secretRef:
              name: influxdb-creds
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: influxdb
        persistentVolumeClaim:
          claimName: influxdb-pvc
