apiVersion: v1
data:
  INFLUXDB_DB: dGVzdGRi
  INFLUXDB_HOST: aW5mbHV4ZGI=
  INFLUXDB_PASSWORD: YmlnYmFzZQ==
  INFLUXDB_USERNAME: YmlnYmFzZQ==
kind: Secret
metadata:
  name: influxdb-creds
  namespace: influx
type: Opaque
---
apiVersion: v1
data:
  GF_SECURITY_ADMIN_PASSWORD: YmlnYmFzZQ==
  GF_SECURITY_ADMIN_USER: YmlnYmFzZQ==
kind: Secret
metadata:
  name: grafana-creds
  namespace: influx
type: Opaque
---
apiVersion: v1
data:
  INFLUXDB_DB: dGVzdGRi
  INFLUXDB_URL: aHR0cDovL2luZmx1eGRiOjgwODY=
  INFLUXDB_USER: YmlnYmFzZQ==
  INFLUXDB_USER_PASSWORD: YmlnYmFzZQ==
kind: Secret
metadata:
  name: telegraf-secrets
  namespace: influx
type: Opaque
